### PR TITLE
Update prompts and add auto-approval

### PR DESCRIPTION
**Pull request by rbuckton**
Adds a new advanced option `alt+a` to set the default approval option:

image

image

image

This is also available as a command-line option via `--approve <manual | auto | always>`:
- `manual` - PRs are approved manually.
- `auto` - PRs are approved when merged if there are no approvals (or if there are approvals but at least one review requires changes).
- `always` - PRs are approved when merged if you haven't already approved the PR.

Adds some UI tweaks for representing changes to options:

**Checkboxes:**
image

**Radio Buttons:**
image

### CODE REVIEW

**Comment by orta** [comment]
The selection option menus are much nicer in this version

**Comment by orta** [comment]
By oldest! yessss

**Comment by rbuckton** [comment]
I thought I'd removed the need for a cancel token.

**Comment by orta** [comment]
Interesting,  I was getting typescript build errors from it not being available

**Comment by rbuckton** [comment]
published as `focus-dt@1.0.3`

**Pull request merged**
